---
- name: Configure PulledPork3
  ansible.builtin.template:
    src: pulledpork.conf.j2
    dest: /usr/local/etc/snort/pulledpork/etc/pulledpork.conf
    owner: root
    group: root
    mode: '0644'

- name: Create Required Folder Structure
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /usr/local/etc/lists
    - /usr/local/etc/rules
    - /usr/local/etc/so_rules

- name: Modify Snort Log Folder
  ansible.builtin.file:
    path: /var/log/snort
    state: directory
    owner: snort
    group: snort
    mode: '5775'

- name: Create Required Files
  ansible.builtin.file:
    path: '{{ item }}'
    state: touch
    owner: root
    group: root
    mode: '0644'
  loop:
    - /usr/local/etc/rules/snort.rules
    - /usr/local/etc/rules/local.rules
    - /usr/local/etc/lists/default.blocklist

- name: Install Snort Rules with PulledPork
  ansible.builtin.command: python3 /usr/local/etc/snort/pulledpork/pulledpork.py -c /usr/local/etc/snort/pulledpork/etc/pulledpork.conf -i
  changed_when: false

- name: Install custom.lua config
  ansible.builtin.copy:
    src: custom.lua
    dest: /usr/local/etc/snort/custom.lua
    owner: root
    group: root
    mode: '0644'

- name: Include custom.lua in snort.lua config
  ansible.builtin.lineinfile:
    path: /usr/local/etc/snort/snort.lua
    line: include 'custom.lua'

- name: Update HOME_NET in snort.lua config
  ansible.builtin.lineinfile:
    path: /usr/local/etc/snort/snort.lua
    regexp: ^HOME_NET = .*
    line: HOME_NET = '[{{ ludus_snort_home_net }}]'

- name: Create Snort Service
  ansible.builtin.template:
    src: snort.service.j2
    dest: /etc/systemd/system/snort.service
    owner: root
    group: root
    mode: '0644'

- name: Start Snort Service
  ansible.builtin.systemd_service:
    name: snort.service
    state: started
    enabled: true
    daemon_reload: true
