---
- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined

- name: Check for Linux
  ansible.builtin.fail:
    msg: This role only supports Debian Linux Operating Systems
  when:
    - ansible_os_family != "Debian"

- name: Preliminary Tasks
  ansible.builtin.include_tasks: prelim.yml
  become: true

- name: Download Snort Source Code
  ansible.builtin.include_tasks: download_source.yml
  become: true

- name: Build Snort Source Code
  ansible.builtin.include_tasks: build_snort.yml
  become: true

- name: Configure Snort Application
  ansible.builtin.include_tasks: configure_snort.yml
  become: true

- name: Clean Up Tasks
  ansible.builtin.include_tasks: cleanup.yml
  become: true
